CREATE TABLE organizations(id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
landline VARCHAR(255) NOT NULL,
mobile VARCHAR(255) NOT NULL,
fax VARCHAR(255) NOT NULL,
PRIMARY KEY (id))